// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApaHSMJMfL5bi5Xd5VQdW1Mg1WkvIFXUg',
    appId: '1:289114548704:android:3b29fa6276c3e767982385',
    messagingSenderId: '289114548704',
    projectId: 'app-job-timer-flutter',
    storageBucket: 'app-job-timer-flutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAW8X0LBbzM11vO12PPWZqkts_Z34D6e3w',
    appId: '1:289114548704:ios:c1b7e8dab65bb1d4982385',
    messagingSenderId: '289114548704',
    projectId: 'app-job-timer-flutter',
    storageBucket: 'app-job-timer-flutter.appspot.com',
    androidClientId: '289114548704-brb90cnerh9cq16l4acfh4ef7s3ho8ld.apps.googleusercontent.com',
    iosClientId: '289114548704-p5osu9g8nsq4qirlpll0qbjo4aplnpkf.apps.googleusercontent.com',
    iosBundleId: 'com.fine.jobTimerApp',
  );
}
